/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://guqqvle5jnarpku5iid34pmgum.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AWS_IAM",
    "aws_appsync_apiKey": "da2-hspiv65rzjfg3ezigctff4sbla",
    "aws_cognito_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:aeda3bce-f0c9-41a0-b397-ac098f11cbfc",
    "aws_user_pools_id": "us-east-1_thZVvdeu4",
    "aws_user_pools_web_client_id": "2u5va7qh5h4gc6erlt0u8c75bp",
    "oauth": {}
};


export default awsmobile;


